export const SHOW_MODAL = 'home/SHOW_MODAL'
export const CLOSE_MODAL = 'home/CLOSE_MODAL'
export const SELECTED_ROW_KEYS = 'home/SELECTED_ROW_KEYS'
export const FORM_Detail = 'home/FORM_Detail'
export const CHANGE_PAGE_SIZE = 'home/CHANGE_PAGE_SIZE'
export const CHANGE_CURRENT = 'home/CHANGE_CURRENT'
